# Generated by Django 6.0.8 on 2026-08-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_currency_userprofile_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='monthly_income',
            new_name='opening_balance',
        ),
    ]
