# Generated by Django 6.0.8 on 2026-08-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='categories.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=10),
        ),
    ]
