# Generated by Django 6.0.8 on 2026-08-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_category_budget_period'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPENT', 'Spent'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='budgets.budget')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_logs', to='expenses.expense')),
            ],
            options={
                'unique_together': {('budget', 'date')},
            },
        ),
    ]
