# Generated by Django 6.0.8 on 2026-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='auto_split_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
