# Generated by Django 6.0.8 on 2026-10-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
