# Generated by Django 6.0.8 on 2026-10-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_options'),
        ('savings', '0002_alter_saving_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_savings', to='income.income'),
        ),
    ]
