# Generated by Django 6.0.8 on 2026-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
